version: "3.8"

services:
  # ---------------------------------------------------------------------------- #
  #                               MongoDB Database                               #
  # ---------------------------------------------------------------------------- #
  mongodb-service:
    image : mongo
    container_name: ${MONGODB_CONTAINER_NAME}
    environment:
      - PUID=1000
      - PGID=1000
    # volumes:
    #   - ./docker/database:/data/db
    #   - ./docker/backup:/backup
    ports:
      - 27010:27017
    restart: unless-stopped
  

  # ---------------------------------------------------------------------------- #
  #                        Node gRPC Database Microservice                       #
  # ---------------------------------------------------------------------------- #
  database-grpc-service:
    # image: grpc/node
    container_name: ${DATABASE_GRPC_CONTAINER_NAME}
    environment:
      - PUID=1000
      - PGID=1000
    # volumes:
    #   - ./database:/app/database
    ports:
      - 50051:50051
    build:
      context: .
      dockerfile: Dockerfile-database
    depends_on:
      - mongodb-service


  # ---------------------------------------------------------------------------- #
  #                           Node Gateway Microservice                          #
  # ---------------------------------------------------------------------------- #
  gateway-service:
    # image: grpc/node
    container_name: ${GATEWAY_CONTAINER_NAME}
    environment:
      - PUID=1000
      - PGID=1000
    # volumes:
    #   - ./gateway:/app/gateway
    ports:
      - 3500:3500
    build:
      context: .
      dockerfile: Dockerfile-gateway
    depends_on:
      - database-grpc-service